# Generated by Django 2.2.3 on 2020-02-28 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artistID', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('genre', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=248)),
                ('LinkToSocialMedia', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('profilePicture', models.ImageField(null=True, upload_to='')),
                ('professional', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('songID', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('album', models.CharField(max_length=128)),
                ('artistName', models.CharField(max_length=128)),
                ('overallScore', models.IntegerField(default=0)),
                ('linkToSong', models.URLField()),
                ('artistID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reviewID', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('review', models.CharField(max_length=248)),
                ('date', models.DateField(auto_now=True)),
                ('score', models.IntegerField(default=0)),
                ('songID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Song')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.User')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('ablumID', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('albumName', models.CharField(max_length=128)),
                ('ablumCover', models.ImageField(null=True, upload_to='')),
                ('artistID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Artist')),
            ],
        ),
    ]
