# Generated by Django 2.2.3 on 2020-03-18 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('albumID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('albumName', models.CharField(max_length=128)),
                ('slug', models.SlugField(default=uuid.uuid1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artistID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('artistName', models.CharField(default='Artist', max_length=128)),
                ('genre', models.CharField(default='Genre', max_length=128)),
                ('description', models.CharField(default='Description', max_length=248)),
                ('LinkToSocialMedia', models.URLField(default='Link')),
                ('slug', models.SlugField(default=uuid.uuid1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('songID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(default='Title', max_length=128)),
                ('artistName', models.CharField(default='ArtistName', max_length=128)),
                ('linkToSong', models.CharField(default='link', max_length=248)),
                ('slug', models.SlugField(default=uuid.uuid1, unique=True)),
                ('albumID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Album')),
                ('artistID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reviewID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('review', models.CharField(max_length=248)),
                ('score', models.IntegerField(default=0)),
                ('songID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Song')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artistID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Artist'),
        ),
    ]
