# Generated by Django 2.2.3 on 2020-03-04 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20200304_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='ablumID',
            new_name='albumID',
        ),
        migrations.RemoveField(
            model_name='album',
            name='ablumCover',
        ),
    ]
