# Generated by Django 2.2.3 on 2020-03-03 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20200303_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='artistID',
        ),
        migrations.RemoveField(
            model_name='album',
            name='ablumCover',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
