# Generated by Django 2.2.3 on 2020-03-17 11:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20200310_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, unique=True),
        ),
    ]
