# Generated by Django 2.2.3 on 2020-03-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_auto_20200304_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='LinkToSocialMedia',
            field=models.URLField(default='Link'),
        ),
        migrations.AddField(
            model_name='artist',
            name='artistName',
            field=models.CharField(default='Artist', max_length=128),
        ),
        migrations.AddField(
            model_name='artist',
            name='description',
            field=models.CharField(default='Description', max_length=248),
        ),
        migrations.AddField(
            model_name='artist',
            name='genre',
            field=models.CharField(default='Genre', max_length=128),
        ),
    ]
