# Generated by Django 2.2.3 on 2020-03-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_auto_20200318_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artistImage',
            field=models.ImageField(default='static/images/artist.jpg', upload_to='C:\\Users\\euanw\\Workspace\\Applausable_WAD2_Group_Project\\static'),
        ),
    ]
