# Generated by Django 2.2.3 on 2020-03-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_song_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='linkToSong',
            field=models.CharField(default='link', max_length=248),
        ),
    ]
