# Generated by Django 2.2.3 on 2020-03-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_artist_artistimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artistImage',
            field=models.ImageField(default='artist.jpg', upload_to='C:\\Users\\euanw\\Workspace\\Applausable_WAD2_Group_Project\\static'),
        ),
    ]
