# Generated by Django 2.2.3 on 2020-03-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0007_song_overallscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('Pop', 'POP'), ('Rock', 'ROCK'), ('Metal', 'METAL'), ('Soul', 'SOUL'), ('Electronic', 'ELECTRONIC'), ('Rap', 'RAP'), ('Hip-Hop', 'HIP-HOP'), ('Indie', 'INDIE'), ('Classical', 'CLASSICAL'), ('Country', 'COUNTRY'), ('Jazz', 'JAZZ')], default='Pop', max_length=15),
        ),
    ]
