# Generated by Django 2.2.3 on 2020-03-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0009_album_albumcover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='albumCover',
            field=models.ImageField(default='default_album.png', upload_to='C:\\Users\\euanw\\Workspace\\Applausable_WAD2_Group_Project\\media/album_covers/'),
        ),
    ]
