# Generated by Django 2.2.3 on 2020-03-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0010_auto_20200329_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='songImage',
            field=models.ImageField(default='default_song.png', upload_to='C:\\Users\\euanw\\Workspace\\Applausable_WAD2_Group_Project\\media/song_images/'),
        ),
    ]
