# Generated by Django 2.2.3 on 2020-03-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0011_song_songimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='albumCover',
            field=models.ImageField(default='default_album.jpg', upload_to='album_covers/'),
        ),
    ]
