# Generated by Django 2.2.3 on 2020-03-31 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0013_auto_20200331_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='songImage',
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('Pop', 'POP'), ('Rock', 'ROCK'), ('Metal', 'METAL'), ('Soul', 'SOUL'), ('Electronic', 'ELECTRONIC'), ('R&B', 'R&B'), ('Reggae', 'REGGAE'), ('Hip-Hop', 'HIP-HOP'), ('Indie', 'INDIE'), ('Classical', 'CLASSICAL'), ('Country', 'COUNTRY'), ('Jazz', 'JAZZ')], default='Pop', max_length=15),
        ),
    ]
