# Generated by Django 2.2.3 on 2020-04-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0017_auto_20200401_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artistImage',
            field=models.ImageField(default='artist.jpg', upload_to='C:\\Users\\euanw\\Workspace\\Applausable_WAD2_Group_Project\\media'),
        ),
    ]
