# Generated by Django 2.2.3 on 2020-04-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0018_auto_20200402_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artistImage',
            field=models.ImageField(default='artist.jpg', upload_to='artist_images/'),
        ),
    ]
